name: Deploy to prod
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd C:\cat-wife & docker stop cat-wife & docker rm cat-wife & docker rmi cat-wife & git pull & docker build . -t cat-wife & docker run -d -e TOKEN=${{ secrets.TOKEN }} -e LLM_URL=${{ secrets.LLM_URL }} --name cat-wife --restart always cat-wife
